name: Comment

on:
  issues:
    types:
    - labeled
    - unlabeled
  pull_request:
    types:
    - labeled
    - unlabeled

jobs:
  give_comment:
    if: startsWith(github.head_ref, 'dependabot') == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      with:
        ref: master
    - name: Send Issue/Pull request comment
      uses: peaceiris/actions-label-commenter@v1.9.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
