name: Label Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  label:
    if: startsWith(github.head_ref, 'renovate') == false
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull request
        uses: TimonVS/pr-labeler-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
